# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

thorn_grow <- function(iter, layers) {
    .Call('_thorn03_thorn_grow', PACKAGE = 'thorn03', iter, layers)
}

